name: go-fortune workflow

on:
  push:
    branches:
      - 'release/v*.*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: alpsaur/go-fortune:${{ github.sha }}

  scan-and-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy scanner
        id: trivy-scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          output: 'trivy-report.txt'
          severity: HIGH
          exit-code: '0'

      - name: Slack Notification on Failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_PHONS }}
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL_ID_PHONS }}
          SLACK_USERNAME: DipSA58 CICD
          SLACK_MESSAGE: |
            *Scan failed - Alphonsus Tay*
            Failed trivy scan, see uploaded report.
          SLACK_COLOR: '#ff0000'

      - name: Slack Notification on Success
        if: success()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_PHONS }}
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL_ID_PHONS }}
          SLACK_USERNAME: DipSA58 CICD
          SLACK_MESSAGE: |
            *Actions URL*: <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|Build and Push>
            *Name*: Alphonsus Tay
            *Matriculation*: A0290884N
            *Email*: alphonsus.tay@gmail.com
            *Git*: ${{ github.server_url }}/${{ github.repository }}
            *Image*: https://hub.docker.com/repository/docker/alpsaur/ghact-go-fortune
