name: go-fortune workflow

on:
  push:
    branches:
      - 'release/v*.*'

jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Trivy Scanner with dynamic severity
      - name: Run Trivy scanner
        id: trivy-scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          trivy-config: trivy.yaml
          format: 'table'
          output: 'trivy-report.txt'
          severity: ${{ secrets.TRIVY_SEVERITY }}
          fail-on-severity: HIGH
          exit-code: '1'

       # Slack Notification on Failure
      - name: Slack Notification on Failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: test
          SLACK_USERNAME: DipSA58 CICD
          SLACK_MESSAGE: |
            *Scan failed - Alphonsus Tay*
            Failed trivy scan, see uploaded report.

      # Upload Trivy Scan Report to Slack
      - name: Upload scan report
        if: success()
        uses: rtCamp/action-slack-upload-file@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: test
          SLACK_FILE_INITIAL_COMMENT: "Scan report by Alphonsus Tay"
          SLACK_FILE_PATHS: trivy-report.txt


         # Slack Notification on Success
      - name: Slack Notification on Success
        if: success()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: test
          SLACK_USERNAME: DipSA58 CICD
          SLACK_TITLE: 'Image build and signed'
          SLACK_MESSAGE: |
            *Name*: Alphonsus Tay
            *Matriculation*: A0290884N
            *Email*: alphonsus.tay@gmail.com
            *Git*: https://github.com/alpsaur/go-fortune
            *Image*: https://hub.docker.com/repository/docker/alpsaur/ghact-go-fortune

      # Docker
      #- name: Build and push Docker image
      #  if: steps.trivy-scan.outcome == 'success'
      #  uses: docker/build-push-action@v2
      #  with:
      #    context: .
      #    file: ./Dockerfile
      #    push: true
      #    tags: alpsaur/go-fortune:${{ github.sha }}


